"""
3D-решатель свободной геометрии — этап 3D-1: геометрия и сетка (план: docs/plan_3d_2026-09-11.md).

Модель = фон-домен + список объектов-примитивов (параллелепипед, цилиндр, труба, сектор трубы,
шар, призма из многоугольника) с материалом, размещением (центр + поворот), направлением
намагничивания, своим размером сетки и приоритетом наложения. gmsh склеивает тела в одну
конформную тетраэдральную сетку; принадлежность ячейки объекту — из карты фрагментов gmsh.
Материалы общие с 2D (`fem2d.model.materials`). Решатель на скалярном потенциале — этап 3D-2.
"""
from magcore.fem3d.mesh import TetMesh3D, orient_cells, signed_volumes6
from magcore.fem3d.objects import (
    CAD_KIND,
    KINDS_3D,
    MAGNET_DIRS_3D,
    PRIMITIVES_3D,
    GeoObject3D,
    MagnetArrows,
    PreviewGeometry,
    StepBody,
    step_bodies,
    auto_domain3d,
    build_object_problem3d,
    object_problem3d_from_mesh,
    contains3d,
    local_signed_distance,
    magnet_axis_at,
    object_axis,
    object_bbox,
    object_volume,
    polygon_area,
    polygon_self_intersects,
    preview_geometry,
    preview_surfaces,
    rotation_matrix,
    sector_span,
    signed_distance,
)
from magcore.fem3d.scene import (
    arrows_payload,
    axis_segment,
    cell_magnet_arrows,
    cell_quantities,
    material_kind,
    pack,
    region_surfaces,
    scene_payload,
    section,
    unpack,
)
from magcore.fem3d.export import write_vtu
from magcore.fem3d.nonlinear import (
    magnet_axial_coenergy,
    restore_field3d,
    solve_nonlinear3d,
    steel_B_of_H,
    steel_coenergy,
    steel_mu_rel,
)
from magcore.fem3d.postprocess import (
    FLUX_MEASURE_T,
    DemagSummary3D,
    ForceTorque3D,
    coenergy,
    demag_summary,
    field_energy,
    flux_loss,
    flux_through_plane,
    force_weight,
    magnet_axial_flux,
    magnetic_force_torque,
    new_magnet_flux,
    plane_polygons,
    section_triangles,
)
from magcore.fem3d.problem import Problem3D, Region3D
from magcore.fem3d.storage import (
    FIELD3D_FORMAT,
    FIELD3D_VERSION,
    SavedField3D,
    field_payload,
    restore_saved_field,
)
from magcore.fem3d.scalar import (
    ScalarField3D,
    assemble_scalar_system,
    evaluate_phi,
    locate_points,
    material_fields,
    p1_gradients,
    solve_linear3d,
)

__all__ = [
    "FIELD3D_FORMAT",
    "FIELD3D_VERSION",
    "SavedField3D",
    "field_payload",
    "restore_saved_field",
    "restore_field3d",
    "object_problem3d_from_mesh",
    "magnet_axial_coenergy",
    "steel_coenergy",
    "FLUX_MEASURE_T",
    "DemagSummary3D",
    "ForceTorque3D",
    "coenergy",
    "demag_summary",
    "field_energy",
    "flux_loss",
    "flux_through_plane",
    "force_weight",
    "magnet_axial_flux",
    "magnetic_force_torque",
    "new_magnet_flux",
    "plane_polygons",
    "section_triangles",
    "preview_surfaces",
    "preview_geometry",
    "PreviewGeometry",
    "MagnetArrows",
    "arrows_payload",
    "axis_segment",
    "cell_magnet_arrows",
    "cell_quantities",
    "material_kind",
    "pack",
    "region_surfaces",
    "scene_payload",
    "section",
    "unpack",
    "write_vtu",
    "solve_nonlinear3d",
    "steel_B_of_H",
    "steel_mu_rel",
    "ScalarField3D",
    "assemble_scalar_system",
    "evaluate_phi",
    "locate_points",
    "material_fields",
    "p1_gradients",
    "solve_linear3d",
    "TetMesh3D",
    "orient_cells",
    "signed_volumes6",
    "CAD_KIND",
    "KINDS_3D",
    "MAGNET_DIRS_3D",
    "PRIMITIVES_3D",
    "GeoObject3D",
    "StepBody",
    "step_bodies",
    "auto_domain3d",
    "build_object_problem3d",
    "contains3d",
    "local_signed_distance",
    "magnet_axis_at",
    "object_axis",
    "object_bbox",
    "object_volume",
    "polygon_area",
    "polygon_self_intersects",
    "rotation_matrix",
    "sector_span",
    "signed_distance",
    "Problem3D",
    "Region3D",
]
